# Block for general settings.
library: general
settings:
    # Time until a timeout in seconds.
    timeout: 9000
    database: 'reports/benchmark.db'
    keepReports: 20
---
# MLPACK:
# A Scalable C++  Machine Learning Library
library: mlpack
methods:
    MLP_FORWARD:
        run: ['metric']
        iteration: 3
        script: methods/mlpack/mlp_forward.py
        format: [csv, txt]
        datasets:
            - files: ['None']
              options:
                input_size: 50000
                hidden_size: 5000
                output_size: 100

    MLP_BACKWARD:
        run: ['metric']
        iteration: 3
        script: methods/mlpack/mlp_backward.py
        format: [csv, txt]
        datasets:
            - files: ['None']
              options:
                input_size: 50000
                hidden_size: 5000
                output_size: 100
